### ISSUE TITLE
Summary option to display total percentage and byte reduction

### ISSUE THREAD

**Issue by jonnyawsom3** [shssoichiro/oxipng#678]
I'm wanting to move away from ECT due to a lack of updates and questionable decisions regarding defaults, however the per-file statistics of oxipng makes for quite a cluttered window and rather hard to see how much of an overall improvement it had. `-q` stops the flood of file paths, but doesn't display anything at all.

I thought I'd ask about a `-S` or `--summary` that would print similar to ECT, allowing for quick comparisons. Something like
```
Processed 107 files
Could not optimize 12 files further
Saved 192.09MB out of 774.25MB (24.81% Smaller)
```

**Comment by TPS** [comment]
This seems complementary to #419, which was solved differently via #488 → #489, but didn't quite do that or this.

**Comment by andrews05** [comment]
Hi @jonnyawsom3 
This could be a useful feature to have. Unfortunately right now, both this and the json-output proposed in #583 require a breaking change to the API before they can be implemented*. So it won't happen before v10.

*Specifically, the `optimize` function will need to return the input and output sizes so that main.rs can aggregate them.

**Comment by TPS** [comment]
@andrews05 Still considering this for v10?

**Comment by andrews05** [comment]
@TPS Not immediately, but changes in v10 will allow us to add this later.

**Comment by andrews05** [comment]
So I'm circling back to this now that I'm on break. What I'm thinking is rather than adding a new option we just make it always print a summary. The default log level would be lowered from INFO to WARN, suppressing the per-file messages unless `-v` is specified. (This may be good anyway, as there's currently no way to lower the log level other than turning it off completely with `-q`).
Thoughts anyone?

**Comment by jonnyawsom3** [comment]
Sounds like a plan. Then the casual user gets a short summary instead of a wall of results, while advanced users can opt in to the wall but still get a nice summary at the end too

**Comment by TPS** [comment]
Rather than so many info switches, maybe use `--info` w/ a parameter?  E.g.:
- `-q` = `--info 0`: no console output as now
- [default] = `--info 1`: this issue's format
- `-v` = `--info 2`: current default "wall of text"
- `-vv` = `--info 3`, `-vvv` = `--info 4`, &c: further levels of console detail (some of which are handled by other switches like `-q` has) all the way upto & including `--debug` (`--info max`)

It's starting to get difficult to [differentiate all the various console outputs requested](https://github.com/oxipng/oxipng/issues/678#issuecomment-2655240437), & this _might_ help organize it all?

**Comment by andrews05** [comment]
@TPS Right, what I'm proposing here is to _avoid_ adding more switches, so we just keep the current `-q` and multiple `-v` switches, which are a fairly standard pattern.
[edit] We could probably change it to adhere to the `RUST_LOG` env var if no switches are provided, though I'm not sure there's any need for that.

**Comment by ace-dent** [comment]
@andrews05 - I've been testing the CI artefact for #758 ... This looks great!
I wonder how the group feels about adding a third line, to report number of files modified?

```text
Files processed: 89
Files modified: 1
Total saved: 1 bytes (0.01%)
```
I appreciate the clean 2 line summary- but then I nearly always use silent `-q`(!)... Just wonder what a new user may expect?...

Or could this be condensed? ... :

```text
Files modified: 0 of 1
Total saved: 0 bytes (0.00%)
```

In terms of piping the output for shell script processing, the 3 lines are easier to parse.

**Comment by jonnyawsom3** [comment]
I'd like to point back to my original post.

```
X Total files
X Modified/Skipped files (there'll probably be less skipped than processed, might make it cleaner) 
Saved X MB (percentage) of X MB Total
```

That gives all the info needed at a glance,  though the more user friendly KB/MB/ect makes script parsing harder than raw bytes... What if the first -v also output raw bytes? You'd get the 'wall of text' too, but you could truncate to the last 3 lines (I assume)

**Comment by ace-dent** [comment]
Would the user expect the total % saved, based on *all* files processed, or just the files Oxipng actually modified?
Edge case: We have a broken PNG image that cannot be parsed, so gets skipped... should the file's size be added to the running total?

🤷 

Whatever decisions are made, we should clarify in the extended help text the precise value meanings. 🙏

**Comment by andrews05** [comment]
How's this?
```
Files processed: 1
Input size: 8773 bytes
Output size: 8773 bytes
Total saved: 0 bytes (0.00%)
(1 file could not be optimized further)
```
I'm trying to make it easily understandable without requiring explanations in the help. Hopefully it's clear that the stats are for all files processed and the number that couldn't be optimised further is just a footnote.

Files that throw an error are not included in the summary at all since they weren't "processed" and you can already see the errors in the output. E.g. the size of a text file that you included by mistake definitely shouldn't be added to the stats, while a "broken" PNG is effectively not a PNG any more. (We could show a count of failed files, I just didn't think it would be useful.)

Regarding "human size" vs raw bytes, I'd personally prefer to just keep it as bytes. This matches what we already output per-file and I don't think it makes sense to switch it based on the `-v` flag. I'm open to opinions here, but note we don't currently have a byte formatter so an extra dependency may be required.

**Comment by ace-dent** [comment]
Thanks @andrews05 for the detailed reply. I'm not sure about the need for Input/ Output size... but hopefully other users will. 🙏

**Comment by jonnyawsom3** [comment]
Thanks for tackling it so quickly, I'm happy with that if it means avoiding a dependency.

**Comment by andrews05** [comment]
@jonnyawsom3 Thoughts on whether the input/output sizes are needed?

**Comment by jonnyawsom3** [comment]
Input size would be nice, I think output size can be skipped since we have bytes saved

**Comment by andrews05** [comment]
Yeah, that's what I was thinking too, but I also feel like the two should go together. I'll leave them both in for now, it won't hurt.
The PR is updated with these changes.

Btw, since you mentioned parsing the output earlier I'll point #583 which I've also just posted a PR for.

**Comment by jonnyawsom3** [comment]
Sounds good to me

**Comment by ace-dent** [comment]
@andrews05 - having savings in bytes is very useful. Input and Output bytes can be quite large numbers.
I prefer a small binary and the least dependencies... but... did you already add a library to handle suffixes (KiB, etc) with https://github.com/oxipng/oxipng/issues/411#issuecomment-3342019298 ...? i.e. ... is that function available for free?

Edit: I suspect the issue is more complex... e.g. reasonable rounding:  In 100 MiB / Out 100 MiB / Saving 1 Byte ...?

**Comment by jonnyawsom3** [comment]
> having savings in bytes is very useful. Input and Output bytes can be quite large numbers.

Bear in mind 30-50% savings aren't uncommon with fast compressed sources, so saved bytes could still be large too

**Comment by andrews05** [comment]
> did you already add a library to handle suffixes (KiB, etc) with [#411 (comment)](https://github.com/oxipng/oxipng/issues/411#issuecomment-3342019298) ...? i.e. ... is that function available for free?

Unfortunately no, that library does parsing only, not formatting.

**Comment by andrews05** [comment]
Thinking about this again, formatting is actually pretty trivial, we don't really need a library for it.
What if we format the savings only? The exact number of bytes can still be determined from the input and output sizes if desired.
```
Files processed: 1
Input size: 26050 bytes
Output size: 8773 bytes
Total saved: 17.28 KB (66.32%)
```

**Comment by jonnyawsom3** [comment]
Looks good to me, easy to know how much was saved at a glance

A few thoughts came to mind:

Right now the per-file output only gives the resulting filesize and the saved percentage `6682365 bytes (23.15% smaller): Test.png`.
Without separately logging the original size, it doesn't seem very useful to me. Thoughts on changing that to formatted "Bytes saved" too? Ace seems to be the script expert, so I'll let them pitch in.

Assuming `(1 file could not be optimized further)` is also added to the end when applicable, I'm wondering if it should count towards Input/Output size if it's not having an impact. I'm leaning towards include, but thought I'd mention it.

If we're disabling the per-file logging by default in favour of the summary, we'll probably want either a progress indicator `xx/xx files processed` or just a `Processing...` placeholder until it's complete.

**Comment by andrews05** [comment]
> Right now the per-file output only gives the resulting filesize and the saved percentage `6682365 bytes (23.15% smaller): Test.png`. Without separately logging the original size, it doesn't seem very useful to me. Thoughts on changing that to formatted "Bytes saved" too? Ace seems to be the script expert, so I'll let them pitch in.

Sure it is, you just multiply 6682365 by 1.2315 to get the original size 😆
J/k, it's a fair point, I'm just not sure if that's really needed now that we have the summary. Scripts can use the upcoming json output if they need per-file details. Open to opinions, though it might be best left for a separate PR.

> Assuming `(1 file could not be optimized further)` is also added to the end when applicable, I'm wondering if it should count towards Input/Output size if it's not having an impact. I'm leaning towards include, but thought I'd mention it.

Yes, files that weren't optimised further were still "processed" and contribute to the stats.

> If we're disabling the per-file logging by default in favour of the summary, we'll probably want either a progress indicator `xx/xx files processed` or just a `Processing...` placeholder until it's complete.

Good point, that did occur to me too. I can look into it.

**Comment by jonnyawsom3** [comment]
> Sure it is, you just multiply 6682365 by 1.2315 to get the original size 😆

I'll be honest, writing that comment at 5am, I never thought of just multiplying it xD

**Comment by ace-dent** [comment]
@andrews05 @jonnyawsom3 My 2¢: 

I think the json option will work fine for scripting. We should prioritise human use/ readability for the summary. I'm not convinced we need much more than the original 2 line output; it would be good to get other user feedback here. (I always use `-q` as Oxipng was too noisy in the past). Perhaps the summary should only show In/Out bytes if we have `-v` set?

The new proposal has bytes saved converted. I presume the suffixes should be [binary](https://en.wikipedia.org/wiki/Kilobyte) B/KiB/MiB, etc.? 

We do need some Progress bar / update / spinner. Even as an experienced user, it is a little disconcerting waiting several minutes without visual feedback... (a few times I resorted to the system monitor to check something was happening!).

**Comment by jonnyawsom3** [comment]
> I think the json option will work fine for scripting. We should prioritise (human) use/ readability for the summary. I'm not convinced we need much more than the original 2 line output

Assuming scripts will use the JSON output, for human readability and low line count we could go back to
```
Files processed: 2
Total saved: 17.28 KiB of 26.05 KiB (66.32%)
(1 file could not be optimized further)
```
If you still want separate lines but good readability
```
Files processed: 2
Input size: 26.05 KiB
Output size: 8.77 KiB
Total saved: 17.28 KiB (66.32%)
(1 file could not be optimized further)
```

I don't have a strong opinion, but I don't want to skip useful info

**Comment by andrews05** [comment]
> The new proposal has bytes saved converted. I presume the suffixes should be [binary](https://en.wikipedia.org/wiki/Kilobyte) B/KiB/MiB, etc.?

Well that's a good question, and I really don't know what they "should" be. I did have it in decimal (SI) but have just changed to binary. (I'm not going to add a switch for it though 😛)

**Comment by andrews05** [comment]
Right, I've added progress printing. Check out the build and let me know what you think.

**Comment by jonnyawsom3** [comment]
```
Files processed: 19/19
Input size: 120680719 bytes
Output size: 113510983 bytes
Total saved: 6.84 MiB (5.94%)
(5 files could not be optimized further)
Dry run, no changes saved.
```
I think the not-optimized message should be outside of the brackets, to match the dry run message.
I assume the dry run message shouldn't have a full stop to match other lines.
When using `-v`, an extra line to seperate the summary from the per-file output would be nice.
Input and Output sizes feel a little overwhelming next to the Saved MiB, I'd say either format them too or higher verbosity.
Total saved could be a live count while processing, not sure how hard that would be though...
Here's a few mockups to get an idea:

In progress (Skipping the percentage during processing might make a live count easier)
```
Files processed: 9/19...
Total saved: 3.44 MiB (4.75%)
```
Input/Output removed
```
Files processed: 19/19
Total saved: 6.84 MiB (5.94%)
5 files could not be optimized further
Dry run, no changes saved
```
Input/Output Formatted (My preference)
```
Files processed: 19/19
Input size: 115.09 MiB
Output size: 108.25 MiB
Total saved: 6.84 MiB (5.94%)
5 files could not be optimized further
Dry run, no changes saved
```
Input/Output moved to `-v`
```
...
571688 bytes (42.60% smaller): Dry run, no output
760372 bytes (41.26% smaller): Dry run, no output

Files processed: 6/6
Input size: 3487490 bytes
Output size: 2098599 bytes
Total saved: 1.32 MiB (39.82%)
2 files could not be optimized further
Dry run, no changes saved
```
Input/Output moved to `-v` with formatting
```
...
571688 bytes (42.60% smaller): Dry run, no output
760372 bytes (41.26% smaller): Dry run, no output

Files processed: 6/6
Input size: 115.09 MiB
Output size: 108.25 MiB
Total saved: 1.32 MiB (39.82%)
2 files could not be optimized further
Dry run, no changes saved
```

**Comment by andrews05** [comment]
> I think the not-optimized message should be outside of the brackets, to match the dry run message.

I wanted to somehow convey the point that the non-optimised ones are still part of main stats, so the idea was that the brackets indicate it's more of a side note rather than a separate stat. Open to ideas here, as long as it doesn't require detailed explanations of how to interpret the output.

> I assume the dry run message shouldn't have a full stop to match other lines.

Done.

> When using `-v`, an extra line to seperate the summary from the per-file output would be nice.

Done (line of dashes).

> Input and Output sizes feel a little overwhelming next to the Saved MiB, I'd say either format them too or higher verbosity.

Hm, I get what you mean I just (personally) want access to the raw byte sizes. Would it still feel overwhelming like this?

```
Input size: 120 MiB (120680719 bytes)
Output size: 114 MiB (113510983 bytes)
Total saved: 6.84 MiB (5.94%)
```
(Not worried about total saved bytes as it can easily be calculated from the input and output)
Or maybe it is best to switch formatting based on `-v`...
[edit] Okay, I've made it switch based on `-v`.

> Total saved could be a live count while processing, not sure how hard that would be though...

That would be nice, but modifying multiple lines runs into a lot of complications which I would say are best to avoid.

**Comment by jonnyawsom3** [comment]
Not too fussed about the brackets, just thought it looked a little neater, up to you.

For some reason putting the raw bytes in brackets slipped my mind, that'd be perfect with me. Then I could use `-v` to inspect single file savings if needed, but still have the easy-read summary at the bottom. Sorry for so many back and fourths on this, I appreciate the quick iterations.

**Comment by andrews05** [comment]
Okay, I've changed it do the bytes in brackets. Hopefully we're all happy now, I admit this has been a lot more involved than I anticipated 😅

**Comment by ace-dent** [comment]
Thanks @andrews05 !
Testing the latest CI artefact - all looks great!! 🙏
Even tried to break the progress 'spinner' by piping stdout (`| cat`), and it handled everything correctly.
